apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello-web-keycloak-canary
  labels:
    app.kubernetes.io/name: hello-web
    app.kubernetes.io/instance: hello-web-keycloak-canary
    platform.swhurl.com/managed: "true"
spec:
  secretName: hello-web-keycloak-canary-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - keycloak-canary-hello.homelab.swhurl.com
