apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: swhurl-try-6
  namespace: swhurl-try-6-staging
spec:
  interval: 30m
  timeout: 3m
  chart:
    spec:
      chart: app-template
      version: 5.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  install:
    remediation:
      retries: 1
  upgrade:
    remediation:
      retries: 1
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/samclement/swhurl-try-6
              tag: 4-04cba50 # {"$imagepolicy": "flux-system:swhurl-try-6-staging:tag"}
              digest: sha256:119cbf6a879f8257f3ec51f5ba0d0896a2b1f8f7f2723b6402a127a6983b9feb # {"$imagepolicy": "flux-system:swhurl-try-6-staging:digest"}
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                - ALL
            env:
              HOST_IP:
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              OTEL_EXPORTER_OTLP_ENDPOINT: http://$(HOST_IP):4318
              OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
              OTEL_SERVICE_NAME: swhurl-try-6
              DATABASE_PATH: /data/app.db
        replicas: 1
        strategy: Recreate
    persistence:
      tmp:
        type: emptyDir
        globalMounts:
        - path: /tmp
      data:
        type: persistentVolumeClaim
        storageClass: local-path-retain
        accessMode: ReadWriteOnce
        size: 1Gi
        retain: true
        globalMounts:
        - path: /data
