apiVersion: v1
data:
    CLICKSTACK_API_KEY: ENC[AES256_GCM,data:LTcUamI+IrdXmz5W8kRxM9senjHyt9WWMW4y0YIT9pJZiHTXUFxRMq4GQQwBhapPtXbVZzuAwP73jJNBvtBOHA==,iv:aepN5PXACIAUyjxYqaQpq2RD4YVKC6ja3luKNWQJjYI=,tag:dQjn8TVuLIHs2YOTp643bQ==,type:str]
kind: Secret
metadata:
    labels:
        platform.swhurl.com/managed: "true"
    name: clickstack-runtime-inputs
    namespace: observability
sops:
    age:
        - recipient: age1u79dp6zjkal33l7rguzqxy66rwykhq90msrw47tf0vy4mu2jh3hsrkmn7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUEkxRDdyYmEwRXZyOWJU
            VXBtQjErdHZ1OWVZZmIxdjFPaysweHJ1ZlNvCjQxZnhGMVJBdXIwSXRXaXY5Uk5H
            ckltSkhYdTV4U3NSK2dtSGFKcjJwU0EKLS0tIC84YVdvdjVyQ01NbzdiMU9kdTM5
            LzBxUGg3amFhLzdmMFdNdUFSV1lpOWMKq0PYCyIgZ5ULHRhkrMwapR946Crm6Xn3
            VHix3gMpdDesbVoF34xIKlbA0vOMCST8OBDF628rYQ2rE18edIljzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T08:35:34Z"
    mac: ENC[AES256_GCM,data:iJr7FPTXNEZMB0/ZYMGwT1zEkvljDhSveDGX+Dtfn3bQJw4C00FEn2VzQxBmM1WifPPw2DqW88zzYOKTFtqCele5tlW7y9r7pqlGJakB+m/s+5pvzbZeyaq8E0eYPGx3YTl5cuExROlXUM27WSUOI/S3Zxy2YhiRa5PL5wk9XY8=,iv:XWUucMG+VCVAirKWKIhOMyJpJMp5Fr5VVPEExscXy6Q=,tag:trHPIASUXVD30+hoecEYRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
