apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:2rEFVWY6XqyW4B1aJKwoSmU6LZITtJ07T8L1yc9gpzt8jWE9Asw458SVOGKK88b16DbgkxOVdbYDo8AfXlHICerbM/wo3e1CWgIczCdVI3hJ4KQi4Sp00letjrMTqwyc,iv:QJQu85txksto9fNhivqN7BvmZUxPkmo4vdFIJBT+DQM=,tag:JZxzlcSItdPBm+YGMZUiMw==,type:str]
    client-secret: ENC[AES256_GCM,data:cdIvQXlnxYFNAlr8XTRRUahOJIQEvRZIrqYhLVjxJPzudRgrfGzs5twbq+JNe846,iv:FdOsgcTROkqoyATallg83PtVDEnHaZWFAL4fHX55my8=,tag:jRezlL7SOYzZxgfWBbtM5w==,type:str]
    cookie-secret: ENC[AES256_GCM,data:f1TCXNi36GpJHMC3UANGmf25aapX0w83iY9fTzoxpR5WVpIqDoKPQfBqIQw=,iv:Q9LDJJ7tqlNqYeJuoHIJfg0BsuJ79RS79x9+r6NvF98=,tag:J/bZSRILrtqTBuSANelKCw==,type:str]
kind: Secret
metadata:
    labels:
        platform.swhurl.com/managed: "true"
    name: oauth2-proxy-shared-secret
    namespace: ingress
sops:
    age:
        - recipient: age1u79dp6zjkal33l7rguzqxy66rwykhq90msrw47tf0vy4mu2jh3hsrkmn7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqU2U1UTZtQU9uSHJqb09Y
            UEJOcDU5ZUNDbWVLUEJMNCtpajNHQW54SUZFCk9tMnQzOFBqeElYKys0c2EvTVFP
            QnRNNWtUOGZHaWxObmdweHg2QUs3Z00KLS0tICt2bUVQTzZLZTd1MENNanBWRHdn
            ckh0Nm90bVhGM0hYdjZ2d3orNzQrQ0kK1UEWyXOjEBkoegFFrK6DlAAvdI3wuQ04
            BG0qMwkMwTbXoHwpC0UDXeUWF/UThkryTQr5vqznYM80NA+zhoLJmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T16:11:19Z"
    mac: ENC[AES256_GCM,data:ZseJuvAvaWdAbU0P4UwvNtmf8JMEf8OtqsRsOifC86DYJM77EFysnbpsjiv2G90D1no+nF6D2znl8jSJkOT02waqL5eg0e4ZATUstDEKgpjfO1JSQd1d8J2H2H9+mUWAZnhjvjf8Deu3m/eC03q/sypn+qqs1NPe/v+LeqON1so=,iv:B/eGS2Pfu/vPZv+C+3AOsQhAD+Uf14RJxKFNSZ7nagA=,tag:fRQJ7cCqtFI6Rr8KVB+//w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
