apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: storage
spec:
  values:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
    consoleIngress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
