apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  values:
    hubble:
      ui:
        ingress:
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
