apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
  namespace: ingress
  labels:
    platform.swhurl.io/managed: "true"
type: Opaque
stringData:
  client-id: "${OIDC_CLIENT_ID}"
  client-secret: "${OIDC_CLIENT_SECRET}"
  cookie-secret: "${OAUTH_COOKIE_SECRET}"
