apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: ingress
spec:
  interval: 30m
  releaseName: oauth2-proxy
  chart:
    spec:
      chart: oauth2-proxy
      version: 10.1.3
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
      interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    config:
      existingSecret: oauth2-proxy-secret
    extraArgs:
      provider: oidc
      oidc-issuer-url: https://accounts.google.com
      redirect-url: https://oauth.homelab.swhurl.com/oauth2/callback
      email-domain: "*"
      cookie-domain: .homelab.swhurl.com
      whitelist-domain: .homelab.swhurl.com
      standard-logging: true
      request-logging: true
      auth-logging: true
      silence-ping-logging: true
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: "${CERT_ISSUER}"
      hosts:
        - oauth.homelab.swhurl.com
      tls:
        - secretName: oauth2-proxy-tls
          hosts:
            - oauth.homelab.swhurl.com
