apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth-signin
  namespace: ingress
spec:
  errors:
    status:
      - "401-403"
    service:
      name: oauth2-proxy
      port: http
    query: /oauth2/start?rd={url}
