apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:IzXHFZ1QQ5A7Dwo7JxzVL3fstwO+jlt5lS6ld1xnsbs+q4mU3iqsfDATbF+f0/d6IAff4k3jdGIKluy9Mf0zeyrlZhZpfTzXM2x634dknho0Zt/iIyUOUZNU/VgilAhojC3dv0T7428Pmiuh86zirpKoBOT8YVihk6/3cR1eiWU=,iv:gWm55KJhRFP35EUn12V/E4kUTIWcbJ4MTl/0896pOmQ=,tag:LolSMdBlN4krJrF/ZhEdHA==,type:str]
    client-secret: ENC[AES256_GCM,data:Bo8f06iud+F7xRKbLKPObXxtI76m3TyFFyTtrz2KiGS5Oqn5wB3u7bjYeR0O0i0qCVLOIcTl03votvq2J+HIDg==,iv:EfYeUAHV5LKCbCywB3tRjcOFnZgqNXmEh86BXh8rPnc=,tag:85RXzXw4Y4kFVbs1xvJdGw==,type:str]
    cookie-secret: ENC[AES256_GCM,data:i5QlzSalIN2RqX6Lh0T1Nhcg4Xa19exBlAjaBqpWAOUG6Hw5SKB8phqkLxD3Lf3h6b4Uh69gGAKG0Fsi,iv:nI0m5eKjeiPAunz3QISJldQvnm3CS62zvIK5rzoDzFE=,tag:9XsZGWPPqT6b5YV79sj44w==,type:str]
kind: Secret
metadata:
    labels:
        platform.swhurl.com/managed: "true"
    name: oauth2-proxy-shared-secret
    namespace: ingress
sops:
    age:
        - recipient: age1u79dp6zjkal33l7rguzqxy66rwykhq90msrw47tf0vy4mu2jh3hsrkmn7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqU2U1UTZtQU9uSHJqb09Y
            UEJOcDU5ZUNDbWVLUEJMNCtpajNHQW54SUZFCk9tMnQzOFBqeElYKys0c2EvTVFP
            QnRNNWtUOGZHaWxObmdweHg2QUs3Z00KLS0tICt2bUVQTzZLZTd1MENNanBWRHdn
            ckh0Nm90bVhGM0hYdjZ2d3orNzQrQ0kK1UEWyXOjEBkoegFFrK6DlAAvdI3wuQ04
            BG0qMwkMwTbXoHwpC0UDXeUWF/UThkryTQr5vqznYM80NA+zhoLJmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T08:35:33Z"
    mac: ENC[AES256_GCM,data:1dIm61/UGOzPvMhqr9Q/pACHc8HlpPVI1Kd1mpAl5fmqKYg3ADuDN+HYF9neRXPF66DqOIMXig9K2lchA7/aRt7R0MhmGAB990f3JAQrILayrdxusqZ3XU8+YGYxpY5qrCiBwfmBaegsyZj7AJkltgGKjNhYoz7StbMTk4LCqUk=,iv:WVEYWV5M9ygSK/uIYNU5WN4R760L/0uUm4SpmCPV0qI=,tag:CWZPHWZ65VE0sKITlSEdeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
