apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-hubble-secret
  namespace: kube-system
  labels:
    platform.swhurl.com/managed: "true"
type: Opaque
stringData:
  client-id: "${HUBBLE_OIDC_CLIENT_ID}"
  client-secret: "${HUBBLE_OIDC_CLIENT_SECRET}"
  cookie-secret: "${OAUTH_COOKIE_SECRET}"
