apiVersion: v1
data:
    HYPERDX_API_KEY: ENC[AES256_GCM,data:FIqON0vOGtp66nTNHoR7DdQ2FAX2qT1OBoClc6A7ObKPmduQvzUhQDTN+LwU5jH9O3B49vGbvGFL/S+oQykHIQ==,iv:YckKJij/4i1lcY8AY3q0R1oveBwG0e3GX0+sA7QX548=,tag:szRsnqq+BydBBpvc6mmLTQ==,type:str]
kind: Secret
metadata:
    labels:
        platform.swhurl.com/managed: "true"
    name: hyperdx-secret
    namespace: logging
sops:
    age:
        - recipient: age1u79dp6zjkal33l7rguzqxy66rwykhq90msrw47tf0vy4mu2jh3hsrkmn7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZ2ZXODFVQWwxTmY0aENQ
            T3BrZkppQlRCTGJnckdCSThXTjZMSFQyamdBCjZCQmx0QlpBcHlQZS9uc0NSYUVo
            aDJMbDNLSjNwb3N0K1NOVXRMVjZqNzgKLS0tIC9jTmttdUpzMFBYcWZ6MEpiNXpK
            QmVYN0FZUzhmU3Nhak5Iemg1RW5hZ2sKKSphqpnOf51hz8eDGK/6X0cMA73/Z5V9
            aoyy+pAcFd5BTjIdE/7GlSscSJrF9AWWlWLOac0K7ZrGxLdJUg1uNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T08:35:34Z"
    mac: ENC[AES256_GCM,data:mCPDHnjbijsiTord/AVzeZanDw/obeN84/vz90nP+cqm+h4YczufuFXmj47MWSe+Zf2sPazVHHfmWlgPQXsGJNRsJibHxNnD6a2Q3DOYZm8SWkVled6SOti0GbDReoiUH05Mtgh8knijBMSD99hhU/nz7EcT8ZQVO/ZfdkUaSx0=,iv:zpgAmq4+uumNpZ7PFmfgY/eznfYqR3SFRFrlXPtHTco=,tag:n4S+AdMOQomkoCXaifAshg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
