apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-keycloak-canary-secret
  namespace: ingress
  labels:
    platform.swhurl.com/managed: "true"
type: Opaque
stringData:
  client-id: "${KEYCLOAK_CANARY_OIDC_CLIENT_ID}"
  client-secret: "${KEYCLOAK_CANARY_OIDC_CLIENT_SECRET}"
  cookie-secret: "${KEYCLOAK_CANARY_OAUTH_COOKIE_SECRET}"
