apiVersion: v1
kind: Namespace
metadata:
  name: platform-system
  labels:
    platform.swhurl.io/managed: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  labels:
    platform.swhurl.io/managed: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    platform.swhurl.io/managed: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    platform.swhurl.io/managed: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    platform.swhurl.io/managed: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    platform.swhurl.io/managed: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-staging
  labels:
    platform.swhurl.io/managed: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps-prod
  labels:
    platform.swhurl.io/managed: "true"
