apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello-web
  namespace: apps-staging
  labels:
    app.kubernetes.io/name: hello-web
    app.kubernetes.io/instance: hello-web
    platform.swhurl.io/managed: "true"
spec:
  secretName: hello-web-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - staging-hello.homelab.swhurl.com
