apiVersion: v1
kind: Namespace
metadata:
  name: platform-system
  labels:
    platform.swhurl.com/managed: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  labels:
    platform.swhurl.com/managed: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    platform.swhurl.com/managed: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    platform.swhurl.com/managed: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    platform.swhurl.com/managed: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage
  labels:
    platform.swhurl.com/managed: "true"
