apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: test-2
  namespace: test-2-prod
spec:
  interval: 30m
  timeout: 3m
  chart:
    spec:
      chart: app-template
      version: 5.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  install:
    remediation:
      retries: 1
  upgrade:
    remediation:
      retries: 1
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/samclement/test-2
              tag: 1-e6a9dab
              digest: sha256:66b6ac3a6f999fce843e4253d207e846a17e91f429c193e387d7d3493b3e05fd
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                - ALL
            env:
              HOST_IP:
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              OTEL_EXPORTER_OTLP_ENDPOINT: http://$(HOST_IP):4318
              OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
              OTEL_SERVICE_NAME: test-2
            probes:
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: 8080
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: 8080
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: 8080
                  periodSeconds: 5
                  failureThreshold: 24
    persistence:
      tmp:
        type: emptyDir
        globalMounts:
        - path: /tmp
    service:
      main:
        controller: main
        ports:
          http:
            port: 8080
    ingress:
      main:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.middlewares: ingress-oauth-auth-shared@kubernetescrd
        hosts:
        - host: test-2.homelab.swhurl.com
          paths:
          - path: /
            service:
              identifier: main
              port: http
        tls:
        - hosts:
          - test-2.homelab.swhurl.com
          secretName: test-2-tls
