apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  interval: 30m
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      version: 8.3.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    provider: aws
    aws:
      region: "${AWS_REGION}"
      credentials:
        accessKey: "${AWS_ACCESS_KEY_ID}"
        secretKey: "${AWS_SECRET_ACCESS_KEY}"
    txtOwnerId: "homelab-cluster"
    policy: "sync"
    domainFilters:
      - "${BASE_RECORD}"
      - '*.${BASE_RECORD}'
    sources:
      - ingress
