apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: storage
spec:
  interval: 30m
  releaseName: minio
  chart:
    spec:
      chart: minio
      version: 5.4.0
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: docker.io/minio/minio
    mode: standalone
    resources:
      requests:
        memory: 512Mi
    replicas: 1
    persistence:
      enabled: true
      size: 20Gi
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "${CERT_ISSUER}"
      path: /
      hosts:
        - minio.homelab.swhurl.com
      tls:
        - secretName: minio-tls
          hosts:
            - minio.homelab.swhurl.com
    consoleIngress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "${CERT_ISSUER}"
      path: /
      hosts:
        - minio-console.homelab.swhurl.com
      tls:
        - secretName: minio-console-tls
          hosts:
            - minio-console.homelab.swhurl.com
