apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab-infrastructure
  namespace: flux-system
spec:
  dependsOn:
    - name: homelab-flux-sources
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: swhurl-platform
  path: ./infrastructure/overlays/home-letsencrypt-prod
  postBuild:
    substituteFrom:
      - kind: Secret
        name: platform-runtime-inputs
        optional: false
  prune: true
  wait: true
  timeout: 20m
