apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab-platform
  namespace: flux-system
spec:
  dependsOn:
    - name: homelab-infrastructure
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: swhurl-platform
  path: ./platform-services/overlays/home
  prune: true
  wait: true
  timeout: 20m
