apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-k8s-daemonset
  namespace: logging
spec:
  interval: 30m
  releaseName: otel-k8s-daemonset
  chart:
    spec:
      chart: opentelemetry-collector
      version: 0.145.0
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
      interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    mode: daemonset
    image:
      repository: otel/opentelemetry-collector-k8s
    presets:
      logsCollection:
        enabled: true
        includeCollectorLogs: true
      kubeletMetrics:
        enabled: true
      hostMetrics:
        enabled: true
      kubernetesAttributes:
        enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    config:
      exporters:
        otlphttp:
          endpoint: http://clickstack-otel-collector.observability.svc.cluster.local:4318
          headers:
            authorization: ${env:HYPERDX_API_KEY}
      service:
        pipelines:
          logs:
            receivers:
              - otlp
              - filelog
            processors:
              - memory_limiter
              - k8sattributes
              - batch
            exporters:
              - otlphttp
          metrics:
            receivers:
              - kubeletstats
              - hostmetrics
            processors:
              - memory_limiter
              - k8sattributes
              - batch
            exporters:
              - otlphttp
    extraEnvs:
      - name: HYPERDX_API_KEY
        valueFrom:
          secretKeyRef:
            name: hyperdx-secret
            key: HYPERDX_API_KEY
    clusterRole:
      create: true
