apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-k8s-cluster
  namespace: logging
spec:
  suspend: true
  interval: 30m
  releaseName: otel-k8s-cluster
  dependsOn:
    - name: otel-k8s-daemonset
      namespace: logging
  chart:
    spec:
      chart: opentelemetry-collector
      version: 0.145.0
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
      interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    mode: deployment
    image:
      repository: otel/opentelemetry-collector-k8s
    presets:
      kubernetesEvents:
        enabled: true
      clusterMetrics:
        enabled: true
      kubernetesAttributes:
        enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    config:
      exporters:
        otlphttp:
          endpoint: ${env:HYPERDX_OTLP_ENDPOINT}
          headers:
            authorization: ${env:HYPERDX_API_KEY}
      service:
        pipelines:
          logs:
            receivers:
              - k8sobjects
            processors:
              - memory_limiter
              - k8sattributes
              - batch
            exporters:
              - otlphttp
          metrics:
            receivers:
              - k8s_cluster
            processors:
              - memory_limiter
              - k8sattributes
              - batch
            exporters:
              - otlphttp
    extraEnvs:
      - name: HYPERDX_API_KEY
        valueFrom:
          secretKeyRef:
            name: hyperdx-secret
            key: HYPERDX_API_KEY
      - name: HYPERDX_OTLP_ENDPOINT
        valueFrom:
          configMapKeyRef:
            name: otel-config-vars
            key: HYPERDX_OTLP_ENDPOINT
    clusterRole:
      create: true
