apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: swhurl-platform
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  # Update this URL for your canonical remote
  url: https://github.com/samclement/swhurl-platform
