apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap-platform-settings.yaml
  - secret-platform-runtime-inputs.sops.yaml
  - helmrepositories.yaml
  - gitrepositories.yaml
