apiVersion: v1
data:
    CLICKSTACK_API_KEY: ENC[AES256_GCM,data:4aVB31pE6aq4rjPovqH7fT17CObBeoqGkwhagHcfl51mHsca4APDzC++cZTg086V,iv:ffd43koEru1AyyRfX1g2jHXkaE82G1BFOg1p1AoxeI0=,tag:YF/n+MVLStd0PQj8YRyrEw==,type:str]
    CLICKSTACK_INGESTION_KEY: ENC[AES256_GCM,data:asK9HH+MWuxJluTETcoRnAeYtoD5AOnMX1U4rfZ2VeAcAfCaJf1aplYHvT6U0sdj,iv:PiKdcxGA5VIuLg0ZMBAhCpQwREaMas+EvQx9lRkKs9c=,tag:ZQwAms7GyEVzvCzwX2tWHw==,type:str]
    OAUTH_COOKIE_SECRET: ENC[AES256_GCM,data:91wczJIhN43SrYC4O0P8EZhwEgGN2aKBwlUu85nhaRsibXsDMu4J0hUak9E=,iv:zV20RnD/7q8Zilb7DP+udyQrCoZcDQ+JM0gnweHrb0A=,tag:o9JTHjnWSZJylg8WIBgpUA==,type:str]
    OAUTH_HOST: ENC[AES256_GCM,data:p57MjCR197XAp3xXSfH+D7uEM5BJodmz9wkV2q7toUI=,iv:pGw8BdHja5Nl4txCvM5sjrCA7Spy5LCtsKZ+ianiyiY=,tag:82sGRS6v34mIX8oT1DelkA==,type:str]
    SHARED_OIDC_CLIENT_ID: ENC[AES256_GCM,data:JQJu1nSJk28JC5NCI1Nx5R+aXwKdQxbiagMqz1Ss5QM6wrenSa6sF4EUs8p6Eqz/MFwOpA7NDAcyHRRgGeToj0wM+FWGrUUeI5dy7OM3r/yGU75FrVr4vRMU5EiLKVha,iv:m2WfvzYznbqmlrSjiSw8dSI7Xw0EVsMVs48xF0LlkDg=,tag:TTH2BFhkBAoYzNv2D6VKcA==,type:str]
    SHARED_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:6w3Rq0ah/XLvxXuGGRSAVGSixR0A+NgFCEi3lyvrmAXA1Al8E+V2GFQt+DSUabk8,iv:IeeWw9uyttIGC3p82IdffvZHv4vH5tY5EDvhk4c7RnA=,tag:NE+jpn8ySE/BzO0l0V46cQ==,type:str]
kind: Secret
metadata:
    name: platform-runtime-inputs
    namespace: flux-system
sops:
    age:
        - recipient: age1u79dp6zjkal33l7rguzqxy66rwykhq90msrw47tf0vy4mu2jh3hsrkmn7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBak1iaFRLbVdsbmZld1Bi
            eDNDaWdEWDd3QzYzektXZWlpUFM1aE9wZFJnCkEwU25XYXVlMzBUZTFRWU8wZkhS
            RWJXTjNCaXM5NlFteGVtUi8wUTRNMW8KLS0tIFBBTEdxRFBPQTdWb2cybXNYNTFT
            RWEyejg0V0Y4UFlXaUMwRnNZcUVmcDQKRP/VRaSws4nLOiwLUjXMgfn1TerV+Xmr
            dXrCYXqbmVnqhYZE9asQ3piixCIAxDDxIB5b866TUqUAnf9Rvtfk3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T08:41:31Z"
    mac: ENC[AES256_GCM,data:C6VA9mGf1oPrgjvUMCvsn+J+3TcGDGSK5/bReJc95Nxvj26g80WgMIqiL0tgtqObnwt5Z5KN6Y5Wz2+p9YkRWHDTD9zePCAjrjfKVK3nmbj57TvC2U+m+XplDq588ZqcI8ded6/jrnd8ZXPpypCEqXL8bQmNgHXQsV2Spr1LFHs=,iv:wDUPG+vZtLuijuI5oBd5Q6HIy/+RdrFMuDwLzco5l04=,tag:2lVlBGPAxYxe92/1Mu5TeA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
