apiVersion: ENC[AES256_GCM,data:xVc=,iv:MWfVptJNmM9JPRfJ4iMdnOmxmV4bh4rCkyScYxBNTCQ=,tag:JAOQI1hkbO7xrYy9Pbc3Ew==,type:str]
kind: ENC[AES256_GCM,data:BYyjZCG7,iv:wafDl/sgQ4BsanwUl1+52hK7KID7NtgvBV/sdRZxiws=,tag:ka1KULQ7+V8UeytvP2bGfg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:43bmjKDcW97R8VW0Tyo6JP51zkwR5DU=,iv:P2J/YC9vYEQdtq2gt8rHl7MITVMD1rzZapWtPJpuNXo=,tag:xBK8ikYSLizzaqdPFOtLTg==,type:str]
    namespace: ENC[AES256_GCM,data:87EYgOPAy0E8+Pk=,iv:C5miLN85gDSWSBj6MD8BCq8EPdnXBhBZC6RfgANuA5g=,tag:v2zlW6gpmxgWSAdQHJQoww==,type:str]
stringData:
    ACME_EMAIL: ENC[AES256_GCM,data:O9UHSMA/fvfddfjooBw=,iv:d7BxubJK/QqB1/PHPdH4f4wNIiB7jUbIZCbXJi+3MIc=,tag:ik8AaKag7vfa6K0ucQ3lCw==,type:str]
    OIDC_ISSUER: ENC[AES256_GCM,data:/Gpx6Ueu0phZqytgyhcL8q3HZJBZ+k0XknR2,iv:gfcxQR/S/8BbGmWnbwSFbYtfxvZmEcX2EZuI+H+05jM=,tag:nh62TsHhurROTLNyYxHVZw==,type:str]
    SHARED_OIDC_CLIENT_ID: ENC[AES256_GCM,data:FybE+bjErTlOn+kbIPY5GmOUP4jUulHlILz6bltD24cMWgZ0vftzZ4Oma9u0zoU90OIWGbOFCybywIGngRWJb7j/vwuZwCXI,iv:6dyPcpn5mU/yASdUWkO0Qgsb8Vghn+NJ6Ks8cdOVa5U=,tag:9aoRUXsC2AJyIIqt5kri1A==,type:str]
    SHARED_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:fSGsOFMi2t6Zp2msgAmrJNN78EoktNliwyUuV8qBtrUFOY8=,iv:8erTfsD2legQakiU6Ox7y/Xd3MQa2f+YY0BMV+BDVOU=,tag:pzvk6EU++ld42Pv1TJUKOg==,type:str]
    OAUTH_COOKIE_SECRET: ENC[AES256_GCM,data:I2xtL9N1jSLvFN7UkVpFXNy9ha6Y0da75HhouhaCbMw=,iv:KrsrgQDcInv5u1lU3ah3q52x9Dzyy5aXsTOcVlukU88=,tag:kMhIs6MPiinghIWf1qmzSQ==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:Omim217A3Jfm,iv:MjOoaiwNHIUutz2mcai7AO1maKGygBQEDq3/HotA0Qk=,tag:u1OwBvAXswX+Cn1QHN6ANQ==,type:str]
    CLICKSTACK_API_KEY: ENC[AES256_GCM,data:MlBHr5aall82I3ehCZCVa39jidiQxl/434wyvBj+FqtieZo=,iv:ElgqSH3O33J3y8oMAqEAgqT9SEosqzv7mvsYVfHsboA=,tag:Cu/mSF7CnWiybS7yUbgKPA==,type:str]
    CLICKSTACK_INGESTION_KEY: ENC[AES256_GCM,data:jbrykAHpckDbSpBfIfV1N6rkoAGkL7tN3H73snLgInna7RAt,iv:lhhemxhrMNEdSDM5WroRfGls3soISE9BJpBe/wwvt6s=,tag:4YPl/YlVHBAhIQoTBsgCGg==,type:str]
    CLICKSTACK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:L5bbk/RYXnaVJc2OWOs=,iv:vtKLek4s12/6Dy+ss80pUbPjCwAkCWboTo/4WPprxYo=,tag:sJmGIDUqAnnfrMJr4jHTVQ==,type:str]
    CLICKSTACK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:bzKdFmyzgLpNG7q7mHbFruVHUQ==,iv:n2ril5N+nOdpI0cQtVB4gk1zHj5vG9FyBCkZCBmEwUI=,tag:DegulTD0irGvEZBDyM9GNQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:dWeMXdiMnPKKkAscgr+A1yPy3Do=,iv:Zhv0UjDzAhd3S8jShxbEyE2ZjVydMkr91F7XXyWNVRI=,tag:sZvmdD9f9dNv7dXgeh04gQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:MLw8VMHPu0C7vdl5ljJI3Z6Kuh9SZpzH4h2VePajGWUgiiSD3R7+qw==,iv:VwmI//XcgeSMNcJU/KZOmYVtJ3H4pzxRHO19zJz5vlU=,tag:n8u0BzWj8mmanIH48n2wZA==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:7QkCXxfgnXj/,iv:03RLO5xVF5D5YJWoHxyqbAwxndjBq/c1OIA2gys/8Fc=,tag:saO+/QOcHMWRXCKKFaYCfA==,type:str]
    AWS_ROUTE_53_HOSTED_ZONE: ENC[AES256_GCM,data:44OJTNMWkrnjN4JUj0cHhOWnJubH,iv:6zwzEzHqbbo8uSBA005BFEXoz67kD1xmGFLszOka2YA=,tag:n3eN954V5xtcwM4kG+H1dg==,type:str]
    KEYCLOAK_CANARY_OIDC_CLIENT_ID: ""
    KEYCLOAK_CANARY_OIDC_CLIENT_SECRET: ""
    KEYCLOAK_CANARY_OAUTH_COOKIE_SECRET: ""
    KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:vkizFnUlw528tMd2/lw/,iv:1rcZkL4pee6CFARvdsdiIwfG8yz3gBMlWW8j1cbtFNo=,tag:GzRvX++xiwiOJUVKJug8Pw==,type:str]
    KEYCLOAK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:DgmmWl8Fh28OmnEm9jOT,iv:Zpy/B9+dLxjcNi0WWPvFneinIkRid4k92AbSehsZcNY=,tag:YJXFgsnhPfiUEL3HIbMymA==,type:str]
sops:
    age:
        - recipient: age1u79dp6zjkal33l7rguzqxy66rwykhq90msrw47tf0vy4mu2jh3hsrkmn7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQVAvclBraWQwZTB4RlZ1
            RXVxZVhOaEdvWE1rSC9kbjFRWEdDOEUzYlh3Cmx6RzFlMmdBbXJIclk0RjkvL0tn
            cE1FZ1lQZmswdXJidGE0aGFwdGF2RkUKLS0tIGZ4Z1JtV0pYQVhrdGFlQWtSN0Uv
            RTBlbnVKK1ZzWmVzOEQwODBhMkVZc1UKhrciOkThlR8c7+gTvHVZcmxyrHKCYn0t
            NP6FpkdHeB7MIrfAF+11AKj4tavXU1T5mOnvma3EiQPwsYE+kR8DFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T23:23:29Z"
    mac: ENC[AES256_GCM,data:MiSGY249ktwo4lGC4xDZZ+10hRaSS70w9jGalD+TMyVPAOGE9codUFz+T0XT4YmTAGP78uVZ/ddY6GXPx2CWTIJJL+MAL0/l2mUl5ywCEPdyrJ6H0x+/BxfuQw97R0r5MnrgMT/rMgyr0AfQjkyU5J7Ji9g2jMbDHAtXIQNmWzc=,iv:O2XeaTUpBxXu0/41p8JlWN5msQyvMQ54TpYVZDTbq6M=,tag:HAFh6yZ8y57WTP0Nb08v+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
