apiVersion: v1
kind: Secret
metadata:
    name: platform-runtime-inputs
    namespace: flux-system
stringData:
    ACME_EMAIL: ENC[AES256_GCM,data:STB5oFnxJMD6W/70sas=,iv:SStqvmc/RHbXTGLuy/YhNms6UtnhvGbEes5CqOd1HjE=,tag:/09N02+LPP15bBUdHaRC/Q==,type:str]
    OIDC_ISSUER: ENC[AES256_GCM,data:epeaHKp5DU+pVL+MxX2E93ItRqjE8l5nAZl5,iv:pcYeQMPXlFAu/9w3o7Mble9jzxt62mXjGuEwUKmYg/s=,tag:Se3xHs1hcBa83QJcOhvTpQ==,type:str]
    SHARED_OIDC_CLIENT_ID: ENC[AES256_GCM,data:gTjXkX53WscJXCiJJMDAxgYRYrxsGAENv9SFpPaZGa4PNf9XEhHMFxM6imjJfgD8QpVRX/FmoKkehU8xzzPr620EK2lt91dZ,iv:GtDQxBPfqb7/GftNc9rAZ4d7pn4VwpjqiBc1gzjzGYs=,tag:PQbEx4SYVWaafxUJ+gMN3g==,type:str]
    SHARED_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:PMyJjvx2I9zzAH28kppe2KsBIxCCqimNfj07m7GF4UuVEzw=,iv:wZcKKXT2n2ymRBWNH3RWrkCpS84a160Mlv/TxEauVKQ=,tag:SKLEquuLwyTiY7Iyxcd9TQ==,type:str]
    OAUTH_COOKIE_SECRET: ENC[AES256_GCM,data:Q7KAHQZSjuFrZUme/18vG2dbZq3AafN2raPNl7a3ZeU=,iv:OUNLvGeIJWUO2qmguRgSVCPbPcLfApobXvFq+ITbXXA=,tag:MCpQXAcAHge8DMo9E6GmQg==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:s+m/zQaHEY5E,iv:474ImaxHMy2yE9DIMvVmfHkTn3GwtDGYtdL5xfL9Tog=,tag:quP/nUbVB74iuIsH20LytQ==,type:str]
    CLICKSTACK_API_KEY: ENC[AES256_GCM,data:3oPuns7QcnO+3hC0dRRxCgEaLFrxJsHdeqJxd33Uf6azNN8=,iv:JceQ3vlSOZTY0SHTEdcKm47ouMz42TDmnvzIsYTygU8=,tag:ClWn4Uh5yaPjWaRNhKO1fw==,type:str]
    CLICKSTACK_INGESTION_KEY: ENC[AES256_GCM,data:xXT9lBclI9VJJEKgwnQBajm46l2h8W4iaLcfDUgJ59XxkgQV,iv:/14tugV09op2br2Xv0Z8wATyl6MKRCsiNtH89k0PY8Y=,tag:PABey+KwThVKemg34sLx8w==,type:str]
    CLICKSTACK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:Sc4q8bA/d4GzR2YIF54=,iv:QlhJ9DqzNKNXOq4e+J7lOk7a75AYPdvTz6XsFYSZoRc=,tag:u+zZxuj7+w6uMKfJ/X4Spw==,type:str]
    CLICKSTACK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:CV5amBuwo30AySQwYNSaS66YKQ==,iv:xLeQ6Z4qTnIur29TJt4TRuPZVIrdHv5BzbcCK18UXUI=,tag:m7WViuRkZF7FR80gWE4P5Q==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:VsoLOPWTUKPHxUIDRvOgq18n1Wg=,iv:9hV9Qf21/zQH8szkeFAc/YYr8lJ1L9+T4VGBo9q18AY=,tag:HttndeJFwaKhi/ePyrUGfQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:i0kKz/E9akXYOVd1Jlto68kJzuFzd6gQTrwLY5tk50poYi17mW2jTA==,iv:HhHwNRAaaZEgEZWsw1le9n1YTX3bqXKU07pbOj3c/F8=,tag:S6VhIUxNtRwtZEEX9cwgMw==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:J7bAUy42luir,iv:BzXZKdbO7io+IVXofbjY5oXa4hOab5PSOhifcOC7ySE=,tag:UFws1qYKSTi0TKEGWLrHug==,type:str]
    AWS_ROUTE_53_HOSTED_ZONE: ENC[AES256_GCM,data:3GBMRTw6ZFryZyixfsb5IBN6Jczh,iv:g0mO/YtvbO9sZe70GFrUI/9YYrNStCj2oSoiXfGnA+g=,tag:QXZ4kJRUSLeJyFzWDwpeWA==,type:str]
    KEYCLOAK_CANARY_OIDC_CLIENT_ID: ""
    KEYCLOAK_CANARY_OIDC_CLIENT_SECRET: ""
    KEYCLOAK_CANARY_OAUTH_COOKIE_SECRET: ""
    KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:c50TBNGevEUdlcQp1q5B,iv:0npGt5z8VMgAxsuVUP2Cqr+mAQzBqmU5OxsWrYrLWbA=,tag:6b6G4VWNHDPftt95B4uwnQ==,type:str]
    KEYCLOAK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:l8fKP2oN3t+Azw1aKoLp,iv:yfHPVg/7uOkpGHpGOmlcaTvIa9BuNyzX1Kv3hRZHiXI=,tag:GF7d+a2veputW5580YtJbQ==,type:str]
sops:
    age:
        - recipient: age1u79dp6zjkal33l7rguzqxy66rwykhq90msrw47tf0vy4mu2jh3hsrkmn7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpT05tSFR3MDZseUwxcTlS
            d01NclpGSDFkaFQ1Smp6OWhBS0NnZno4T1JvCjhTUVdHVnlpeWtjN2JraUVqaGV1
            cHBaZG43UGp0MkNEL2JRS2MxT2lHZTAKLS0tIDNWU2Z1aCthZzI1NXRzTFdIcHFF
            R2d3VHQ5c1NxemNZdyszaEZ1TlpPSlkKxwbvb7t7CdcAbbS2WAxiDSfKik1uYadP
            4NrCx7PN3JqiSfBBSCUJgbClNqAndMy6ucgsH8nYtfWDsEL5sMPmbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T23:39:35Z"
    mac: ENC[AES256_GCM,data:SULicvZ0HxYxtS9DO6/RMuGMDRpcI/WdXMYPMIfj33+krcvTW4ehNKjMFRB/oCenxGbYlaOcxwM/E4cQdTdjDs/hT5nC9JqCDMiUbJig2qnYib5icnlREiBYcE0GxsklTHpulxf1wiNZxVqs0pONECeG6nrblirsz9yTMgi/API=,iv:Dt9isIwKFxoh2t0u2XoAmRffNn5AbA0NQbCgMwZWrmo=,tag:8NV82ZH5B8Dp/rpoikWIxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
