apiVersion: v1
kind: Namespace
metadata:
  name: swhurl-try-1-staging
  labels:
    platform.swhurl.com/managed: 'true'
    platform.swhurl.com/app: swhurl-try-1
    platform.swhurl.com/environment: staging
    platform.swhurl.com/exposure: authenticated-web
