apiVersion: v1
kind: Secret
metadata:
    name: notification-ntfy
    namespace: console
type: Opaque
stringData:
    NTFY_FAILURES_URL: ENC[AES256_GCM,data:KF4/sHdC+16q5i9ckLyw3x3O9bSYL0WMCoVz14rRicN2RYtxyataDlGpQ3Ls/ws=,iv:G1snRhAcJmkPY9D0DrTZvQyJ0dy1Bq3xQgEGGApevXw=,tag:BfkdtuvKv93yIE3HvilR8w==,type:str]
    NTFY_DEPLOYS_URL: ENC[AES256_GCM,data:wKaYORt++8lP+PG+LXAak0UsBIvAxMgA+zh01nr2PZbfBfQo/D1PyqpyMtBJKmU=,iv:lIzLXvpLaiSzk0RGviIVSV6Sp2wL+aHXjiArXQe3Grw=,tag:clr/yZtdAYrdlb0BL364yQ==,type:str]
sops:
    age:
        - recipient: age1u79dp6zjkal33l7rguzqxy66rwykhq90msrw47tf0vy4mu2jh3hsrkmn7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGa1Q1UmRsWjJpRFBwZVdz
            RFBWdDV0WHNacVBuOGVVY0NNbjVIVW9YeGdJCmEwVm5Qc2hhS3B1c0I2c2E3RWZi
            V3JTd1BlRDhTOG5jbGxDViticnRtQ2cKLS0tIE9nc2RwYjY3SklMbnlHUWF0ajNX
            NlBGSGhwUzJSZWlMcE9Ha1EyNDhLR0UK7vkj5izwD8/fLYtUHRmUL6NK4HwshFmd
            lkbO8nZb7RdaV5daikMwv9lkeX93K2DV9z1Jrgj+lGZaPGwQGV7ZMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-03T08:04:26Z"
    mac: ENC[AES256_GCM,data:cPL3kPTu6pByUc4HpnN8zHOomMFoEuzWfhRz9U8ysVnDS/3m08h0Xjnsb6huvk2/uibQexNf0AL2GyYbzhOoj3xuzfLcpuvqZu0dN2i33enOe54TPFmwd08a8UAsa1IGY4TVAh54iITh89izdfynWA/O+O0AqozohDiBukcVaCw=,iv:yajJIGTJxyNjNa7AixqaQZaAnbySY4Lo4r3/IFosJ/U=,tag:gjOGyfiK9G9xPUN6LgcjYA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
