apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: storage
spec:
  # Safety default: keep HelmRelease suspended until migration cutover from legacy Helmfile.
  suspend: true
  interval: 30m
  releaseName: minio
  chart:
    spec:
      chart: minio
      version: 5.4.0
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # TODO(migration): replace scaffold defaults with environment-driven substitution
    # (MINIO_* hosts/credentials, issuer/provider, and feature gating).
    mode: standalone
    existingSecret: minio-creds
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: selfsigned
      hosts:
        - minio.example.invalid
      tls:
        - secretName: minio-tls
          hosts:
            - minio.example.invalid
    consoleIngress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: selfsigned
      hosts:
        - minio-console.example.invalid
      tls:
        - secretName: minio-console-tls
          hosts:
            - minio-console.example.invalid
