apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    platform.swhurl.io/managed: "true"
spec:
  acme:
    email: ops@homelab.swhurl.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-account-key-staging
    solvers:
      - http01:
          ingress:
            class: nginx
