apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    platform.swhurl.io/managed: "true"
spec:
  acme:
    email: "${ACME_EMAIL}"
    server: "${LETSENCRYPT_STAGING_SERVER}"
    privateKeySecretRef:
      name: acme-account-key-staging
    solvers:
      - http01:
          ingress:
            class: nginx
