apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  releaseName: cilium
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: hubble-relay
              namespace: kube-system
            patch: |
              - op: add
                path: /spec/template/spec/hostNetwork
                value: true
              - op: add
                path: /spec/template/spec/dnsPolicy
                value: ClusterFirstWithHostNet
  chart:
    spec:
      chart: cilium
      version: 1.19.0
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    kubeProxyReplacement: "false"
    operator:
      replicas: 1
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-staging
            nginx.ingress.kubernetes.io/auth-url: https://oauth.homelab.swhurl.com/oauth2/auth
            nginx.ingress.kubernetes.io/auth-signin: https://oauth.homelab.swhurl.com/oauth2/start?rd=$scheme://$host$request_uri
          hosts:
            - hubble.homelab.swhurl.com
          tls:
            - secretName: hubble-ui-tls
              hosts:
                - hubble.homelab.swhurl.com
