apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rbac.yaml
  - state.yaml
  - networkpolicy.yaml
  - secret.sops.yaml
  - secret-clickhouse.sops.yaml
  - secret-ntfy.sops.yaml
  - helmrelease.yaml
