apiVersion: v1
kind: Secret
metadata:
    name: incident-review-openai
    namespace: incident-review
type: Opaque
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:DnTVDQRpfQ3dcQ==,iv:Uml5zpOixAc9r4Cl2FipJNPpcOjS4uhm+IxEoyVTKO8=,tag:S33V3muLVicjIReD62ZD7A==,type:str]
sops:
    age:
        - recipient: age1u79dp6zjkal33l7rguzqxy66rwykhq90msrw47tf0vy4mu2jh3hsrkmn7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZak52ZTU3UGlMRnZJTG9M
            blFsdE1zMjN5WlVhd0hEaExXN08xUG9RSGo0Ck1nK0FXOEJjMVZXb1VUVUU3aVFV
            MGd1bkRmbis4aWUwa095VDd4d2FGQkEKLS0tIDV2a0N6eUN4RjVJSngyUXZwcGFm
            a3BlMWRhRHRDZXBuR2FpUUlvL3M5TU0K4p8qbLaytNgQSxSHDAnf3RSHqR2NZRJ3
            mDrHaJipEeNNUwCLMJLL1TvDL/ZplUCk3m01Wt3Zxo6ThxbKzzB4bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-08T02:07:15Z"
    mac: ENC[AES256_GCM,data:7yLfDqFvP88GOWUUESMs9e9sXc6uuOtCpD06Sxk5tLlMrinw0EKMxfwLZ/P/P8iwKnWwLbbzFw1b4xA4SkKBOznl+pHRpiPfFEQE6VJcZBhKToBvBYjbiuiUZyMMN6cJRLPOLUMvIC5BLz/BQGktD7vaVd3skg6rd4cOtuEw1TA=,iv:dZ5aa55k+rhtSZgzgaPjbhUcNVeLFO+1MBCnpcgVNes=,tag:LFWg4CzqFt+n3ausPBZaFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
