apiVersion: v1
kind: Secret
metadata:
    name: incident-review-openai
    namespace: incident-review
type: Opaque
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:0f5+wniFwKTYAvOGCqe9RiZxsVZ0nCXDJJdoz7WdJ3peuI7bsd2gUiyK/jkqeRJOOawy3PRDxKTcqIRVTJ8SrEs3hOgDMYqmAxhUxKHgAtsaMGgKVZ8kr4KcstarmVUUakoxhxcf5esL0mDG4t08V8MFQ9wXPayb8zCvsNEpDLljJ6qZeVvS97fREfXBnQ54c4uJCjOBZRedXW1LYiHrd8bKKkOrAKU=,iv://ezduWIdaP9LSFFIpbgFlmzHilpuwmjNRRwjw6REQM=,tag:gYzH30WLALsbUn+Y4666Bg==,type:str]
sops:
    age:
        - recipient: age1u79dp6zjkal33l7rguzqxy66rwykhq90msrw47tf0vy4mu2jh3hsrkmn7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZak52ZTU3UGlMRnZJTG9M
            blFsdE1zMjN5WlVhd0hEaExXN08xUG9RSGo0Ck1nK0FXOEJjMVZXb1VUVUU3aVFV
            MGd1bkRmbis4aWUwa095VDd4d2FGQkEKLS0tIDV2a0N6eUN4RjVJSngyUXZwcGFm
            a3BlMWRhRHRDZXBuR2FpUUlvL3M5TU0K4p8qbLaytNgQSxSHDAnf3RSHqR2NZRJ3
            mDrHaJipEeNNUwCLMJLL1TvDL/ZplUCk3m01Wt3Zxo6ThxbKzzB4bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-08T02:35:13Z"
    mac: ENC[AES256_GCM,data:nYEjN32rMArmqvqsNcvbePx0s1P7IlqJaUyaEEm5kZ5tTlpbrg5czbSUgluNGsmS+tyC8MoWIGTU0inFIVz/wi+i5Z+yDRC8Xjxk7AHVgvDAvKMViQNB8Tz/u1jSoICYaA1Pc0tEIHBKpyNTMnncKayDhSsrqANO3JpYBKi/uEc=,iv:vQdb/bcH1bC0DqnDhBZUZcVqCyADWw12rT3o59VauiU=,tag:u3/l2ZumLgzlpD+++cw0mg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
