apiVersion: v1
kind: Secret
metadata:
    name: incident-review-ntfy
    namespace: incident-review
type: Opaque
stringData:
    NTFY_REVIEW_URL: ENC[AES256_GCM,data:79FNu0UtPn8i3tBvRW7bzHU5D2fkbHeoBbgSeiHoAU1qFah071V/R4XwbeJ5G3plwQ==,iv:TDVgUqd7McmXkX7LYeQmuT2QE+gxHJlvlD1YwMtkSc8=,tag:pST11YS+E1dPDNXZyudCeg==,type:str]
sops:
    age:
        - recipient: age1u79dp6zjkal33l7rguzqxy66rwykhq90msrw47tf0vy4mu2jh3hsrkmn7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWFdDM3owVXN6bDkzNnJX
            L3A2TE8rMGg3dmRRcDBZbUFwTFYvWEJTbmc0CnowS2Z2MGVhSWFXdnkwT3kveVNL
            cmVodjhaUDFpSzd6OUxCRHpZbHJjMGMKLS0tIFVjNmVLc2sxcFV0dTJrcndWUVky
            NUZBUkVnTFluRkxsdDZHbm9YWFZTT2cKl8UGL4TzQabKeUdKMvfqIUbnC8E3S6+J
            2n+24TmUfTHqP7U6SROusiXElDbj+BelZggNOz/Rl2G+b0wIDPx1lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-08T02:07:15Z"
    mac: ENC[AES256_GCM,data:3eohzzyjtdqlCVMHN6U6l8taoI36nNAk389ABmgdV7ZNy5dLszlANIEGoPOpxwpag548kRoffj0ccB+z+W9iYzlufFnbcmhmzoee5lfAZ4gbiOlgt/FrSmw9x9Vm6uzgmHMoJoLysPleI1NRfrljYCWJtWVUfzkl4jk9ysUWA8A=,iv:dQLN4JEs2+WqPLDd7kwW7N9XxxmkuMlsaYCX9qXsZvI=,tag:5vuXBkhb5na0y4M7RDw5nQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
