apiVersion: v1
kind: Secret
metadata:
    name: incident-review-clickhouse
    namespace: incident-review
type: Opaque
stringData:
    CLICKHOUSE_USER: ENC[AES256_GCM,data:7zoa,iv:6VlfcQ2/Yqw2FjcWyweTvbj4O96ILKZNEjMPDL+l1Og=,tag:9XUBYIivoZ1qXPER3jIYlg==,type:str]
    CLICKHOUSE_PASSWORD: ENC[AES256_GCM,data:HkchUPT2wllb3iQ3IHxfhKJgJ6nyNMZZSCa2lUj4HY5uiOs2Krf/AyQTHL3qDd6z,iv:zQiqwQ9RZUj549pkpwZOphGp809EBMctO/IfOpA5Zpk=,tag:BaRGShICezJy43CNwf7BJw==,type:str]
sops:
    age:
        - recipient: age1u79dp6zjkal33l7rguzqxy66rwykhq90msrw47tf0vy4mu2jh3hsrkmn7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwaDJRQXcrY25kaElIQ3BK
            aFZHNGRXWndKZUdkVWhFMFVWSmF2UXJqZ1FVCklMa01mTEc0TzJXTTUrRWJwbjVj
            RWxNcW9aYzZXTCtESFVrZHJDUElYWVkKLS0tIHl3cGsxeGIzcnFsaVBXRGl4aWZl
            SVlYc3plQVpDYVB6NUIyVllYQ0ZDOWsKUUPJwyMw59ONMXhaH1lkoOHbiJJpI9Qy
            xWwjdm4Qzq+eEs9ZDpeJnQ53Z5lIdZib9inxV6uIQKOFYa2pf64oVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-08T02:07:15Z"
    mac: ENC[AES256_GCM,data:b6BKxnTPZZnC9b6us6vgsy+fUoTAMjdm6PUKa1ViQtSn47feJDGpkZuq1wTEddH08m9pSKq3tnOw5zhv8GPvL2Ayuz40skjZpOeYfVUTxPup8lw03zpf+/I9uMZcA/rYU2q3eI7SDy1a9joqwYikYRqpypri3jpP/U75Owh977g=,iv:p1vbjlLM0bqdBI3DhFNwQky3kBvB69FAlE6V9fIDQCU=,tag:WTVxKsPjFZv1M7nLc49AEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
