"""The web console: app instances, Flux units and cluster health (docs/plan.md section 7).

``cluster`` reads the cluster through a Runner (no Secrets, no exec);
``server`` serves it. Reads use this package's own code; changes will go
through PRs generated by the tooling in a clone of ``main``.
"""
