apiVersion: v1
kind: Namespace
metadata:
  name: swhurl-try-6-prod
  labels:
    platform.swhurl.com/promotion-test: 'true'
    platform.swhurl.com/managed: 'true'
    platform.swhurl.com/app: swhurl-try-6
    platform.swhurl.com/environment: prod
    platform.swhurl.com/exposure: private
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
