apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: app-swhurl-try-6-production
  namespace: flux-system
spec:
  providerRef:
    name: ntfy-deploys
  eventSeverity: info
  eventSources:
  - kind: HelmRelease
    name: swhurl-try-6
    namespace: swhurl-try-6-prod
  inclusionList:
  - .*succeeded.*
