apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-promote-test-prod
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-base
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: swhurl-platform
  path: ./apps/promote-test/prod
  prune: true
  wait: true
  timeout: 10m
