apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab-infrastructure
  namespace: flux-system
spec:
  dependsOn:
    - name: homelab-flux-sources
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: swhurl-platform
  path: ./infrastructure/overlays/home
  postBuild:
    substitute:
      quote: '"'
    substituteFrom:
      - kind: ConfigMap
        name: platform-settings
        optional: false
      - kind: Secret
        name: platform-runtime-inputs
        optional: false
  prune: true
  wait: true
  timeout: 20m
  healthChecks:
    - kind: Deployment
      name: cert-manager
      namespace: cert-manager
    - kind: Deployment
      name: traefik
      namespace: kube-system
    - kind: Deployment
      name: minio
      namespace: storage
    - kind: Deployment
      name: external-dns
      namespace: kube-system
