apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infra.yaml
  - platform.yaml
  - app-hello-staging.yaml
  - app-hello-prod.yaml
  - app-hello-ts-staging.yaml
  - app-hello-ts-prod.yaml
  - app-test-2-staging.yaml
  - app-test-2-prod.yaml
  - app-test-3-staging.yaml
