apiVersion: v1
kind: Secret
metadata:
    name: clickstack-runtime-inputs
    namespace: observability
    labels:
        platform.swhurl.com/managed: "true"
type: Opaque
stringData:
    #ENC[AES256_GCM,data:waLFq8q9hjguKgjG3kym/SlWf0JFtuwm347a9hLSIZFd+ZSRbtFc4rdDTCpLjbtGb8iPPGNyhKnVz3fDCTIDPSCWSzxU,iv:aaYY8JDPHbTD7CaFQAl63rZWIGuoIiQodgzh/CbKyCc=,tag:vHKka5S5eqDqoKQHn7mq1w==,type:comment]
    #ENC[AES256_GCM,data:UMdKGhbchTjuFTLoy4bt9o1MflutaYo2M7/bYa4CeoOtB1EqFyZ3cKJX+d/vuCSqgkhO89YjB4MolYeHOHwzt2mLiD0DL5ZbxKCk,iv:OQDqXPBQvhOC5jaCtCYRl0Q9KqRXVBWep4UKBCw07VE=,tag:HDvtUO1GobH+7/PSynRAwA==,type:comment]
    CLICKSTACK_INGESTION_KEY: ENC[AES256_GCM,data:6I81tIADONI6eVsdWCj8oHJoy9MB4p6k9ygqeFYiqQk61lfO,iv:fvgbHI26fgTQBEYEB61IM14mWmVGCRzkGKvxVkj2Sng=,tag:JdA0LsFxUZjs1DtRNBXn9g==,type:str]
    #ENC[AES256_GCM,data:ZT2mSp9MSS3ofK+lhAKABW7XQtIEN9yyOpV7pI9vD10Wida3cl7DLdDtv0b0v1iOPFRLkKdtmCPnPinzb8keAMsmfjeeo53N,iv:CMmpXaMkk+5VjjnENGlkYmDdvGks5iD7rZ8TdO5WPqY=,tag:RCAVZ6R43necljFSXdSWnA==,type:comment]
    CLICKSTACK_ADMIN_EMAIL: ENC[AES256_GCM,data:vyAHYASRPgDYFB2YI0U=,iv:uB/YpAZMKFRJ/eogGiYGOYRXSZxWgMbgkxuUYaimtEw=,tag:YLMe/iEE7Ly1JB3UaifiyQ==,type:str]
    CLICKSTACK_ADMIN_PASSWORD: ENC[AES256_GCM,data:1TCwPhwmi/ra806I6KZz9Lr0t7IXbXGk+ePSRBgwp9GHt6Wy,iv:XqFiF/kVkm0wcz2537A8z5Y8CcdztjfTfdfjoRjEjVw=,tag:ZV+UnrVoOqMe0tys6z9j9A==,type:str]
    #ENC[AES256_GCM,data:i2EROxrGhNhjzxQ1X2jx+nFL9Br3xpG+ZDyB/fpEjPxXEE6byFT8j1lsR8o4SGludx2iR0Djj8LPum0Zl73V1iFg,iv:n9ySpsag52MAIeoWjBvbwI1bjlKDI4IgJlP7wGNfeX4=,tag:56HWDrjhUozokBUrwYr71A==,type:comment]
    MONGODB_PASSWORD: ENC[AES256_GCM,data:/J2gSzM3kXpPLhHUzqR+HTIxtSmmh+yTz1ucK6lH+bjoc28VI2/jaO57AhU/kk6H,iv:up/nOSB3mkqIxrbGNFoEdO2JaPf4Kjik3GwWfL5uDU8=,tag:J/h17qIGJZuH0cQUDw5oGw==,type:str]
    CLICKHOUSE_PASSWORD: ENC[AES256_GCM,data:oieFF63xhook9CUSKiQcU7FJVDspkBPo9fNx5B++fF70Vsy1WRYfD8zDGQWKbskt,iv:Cs1vlh0+kXtopEifymmMQjVfBQMyUmOavuVG/thazVg=,tag:m1tZKH6h9D9xUdfcqjE42A==,type:str]
    CLICKHOUSE_APP_PASSWORD: ENC[AES256_GCM,data:mrzTDD0Jxa8FcEJsXMu/wILQ3cvbo0zjy7muKWCHmDGOlBdZzv/3SjLT0VZSvHY1,iv:zdopZucwltlnRhSYF+xyssamWNoijnlIryjpAju7XHA=,tag:FLUlcbLeG7aBddIVKEjzHg==,type:str]
sops:
    age:
        - recipient: age1u79dp6zjkal33l7rguzqxy66rwykhq90msrw47tf0vy4mu2jh3hsrkmn7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMGNaSWJHZVhCNDBVOEFV
            ZlErdmpxOXlsSzhHT1lMbGQ0dnNSQSt6cUJvCnBmcU8ycjdlbHdmUEVZRWxHL0V2
            VXg0V0xxZGZJVzhxR1A1RzRuOTloZ2cKLS0tIExDSnBMV0laOFBYTzIyaStQR0t2
            VUltZ3YyWGJnZi9ndGszK2dOWDZWVlkKgzDPQUZd8gpwqjgz4Jn9cnyMNgPqbvt8
            dVuV5o69ZB2mml9PlLwJurMSD/s0yQDeAIcZoofYren6vBXqfEhRIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T06:08:01Z"
    mac: ENC[AES256_GCM,data:hnjdjgOS5G7UJJMB331GeZpwNoijyyuJGip2ZHoueoWNPRdSWWkR/31kX1+RD2pm3Cs3ZJYBSvS+KTodHSrhGbd2dhroU4Fr/hmp4coM5laCornozA8M77qXwCeNowBMqEh8R1KSWw7ZRrlfl3IbDMMbRibR+4pOCtIKCgSX48M=,iv:B7ixjFXvLJ03fRcO+a6QyrwrcwsXjfpQvroz8NmeS+M=,tag:ylhKtXFvC0pK68nefLOh0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
