apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    platform.swhurl.com/managed: "true"
spec:
  acme:
    email: ops@homelab.swhurl.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-account-key-prod
    solvers:
      - http01:
          ingress:
            class: nginx
