apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 30m
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: v1.19.3
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    crds:
      enabled: true
    startupapicheck:
      enabled: false
    labels:
      platform.swhurl.io/managed: "true"
