apiVersion: v1
data:
    HYPERDX_API_KEY: ENC[AES256_GCM,data:dBhM/7Ob61GCyS3W+ilPU0GAbFbrsSpqW4haaNIzcdsjl4Gr/kLhop8vjRdd3Kui,iv:5bi3l6IkT5LQ8UfV1oYiIVHc+/vJeNkb7ym+3fSmFRI=,tag:p49yUYufR2d7I0T0be5D9g==,type:str]
kind: Secret
metadata:
    labels:
        platform.swhurl.com/managed: "true"
    name: hyperdx-secret
    namespace: logging
sops:
    age:
        - recipient: age1u79dp6zjkal33l7rguzqxy66rwykhq90msrw47tf0vy4mu2jh3hsrkmn7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZ2ZXODFVQWwxTmY0aENQ
            T3BrZkppQlRCTGJnckdCSThXTjZMSFQyamdBCjZCQmx0QlpBcHlQZS9uc0NSYUVo
            aDJMbDNLSjNwb3N0K1NOVXRMVjZqNzgKLS0tIC9jTmttdUpzMFBYcWZ6MEpiNXpK
            QmVYN0FZUzhmU3Nhak5Iemg1RW5hZ2sKKSphqpnOf51hz8eDGK/6X0cMA73/Z5V9
            aoyy+pAcFd5BTjIdE/7GlSscSJrF9AWWlWLOac0K7ZrGxLdJUg1uNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-27T21:42:16Z"
    mac: ENC[AES256_GCM,data:rK/j3GOdzguf6g6Awg1MI92P0/RO6Yft5waUx94pyqAwUGLnBXdNMEcvAsSD1iKycfditkMVLaVA9iZHZj6OZXFraKBUI6yG59TtEHrklhJUy4zVrsu7zBl1FGe0Qn9Cl2OodW7TNHA7Ese8oA5QIzBYL1JFtgRN/aygBm3rBt4=,iv:daWwwVqmoFBEJJkKGaS2VpZ5vuSqGo+lusd3xyvUMow=,tag:4QO0G80p8txjADGEPXjK+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
