apiVersion: v1
kind: Secret
metadata:
    name: clickstack-ingestion-key
    namespace: logging
    labels:
        platform.swhurl.com/managed: "true"
type: Opaque
stringData:
    #ENC[AES256_GCM,data:ZRRtYBGHQajDOFcJdzzn45MX/RpASX/AFKcppaFJo0UE8b2NNHooAD8det5H1PwlQksG+WZubQXf,iv:5NkLw7J7VCE0wfBMbjyrvg9WJehSV5lLyex6Sug1hMU=,tag:jpL/17pDkfdYWZ1vTtgQuA==,type:comment]
    CLICKSTACK_INGESTION_KEY: ENC[AES256_GCM,data:y6ESZXMHXaD5u+ODhETj3ijR7S9bbrJELstTxasSkUZpe/Yv,iv:hBCZUb5cp9jX6UzbhHXLYQECP4psu5ZBd07OsNDuhvk=,tag:ukYGEIpyNaa1+2OqiSlyLQ==,type:str]
sops:
    age:
        - recipient: age1u79dp6zjkal33l7rguzqxy66rwykhq90msrw47tf0vy4mu2jh3hsrkmn7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTkNMS1d1N0VjejB0aFlj
            c1FmaFBFMFdMangwNlF0L1JqSldYd0wzRVRvClNsQmxSTi91YytudEVGeEZaRmtj
            VDYyUDg4THR0cWROME9PZ0t3bmJCdk0KLS0tIHVaSGFQUld6dVVTT28zOUJvd1Fi
            WUdxdVNaNWlZZUZJTk53VElzYSs2VjAK5fmo4t4f8CuE8SkuB+Btq20iLHAbTHj8
            vg+ct9SozigW1PrvqxagEkRAGsJBf1c/uoBHzxcAB+b/Wul7pZEjQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T06:08:01Z"
    mac: ENC[AES256_GCM,data:nIcfv0FcS8VOMqnjTueJIOuDf6SwBNiuwdma/A5npeypWbDh4RFgYL0L/Akim+ffYERRP4Ab9MPxXFeMAnXYT6qK09mA/Olodou0NJOYjrGUMgC25Y9c4jWVwCEsD1Bcd/HQJWvEKBgZnPOdQMY4X87zaf0xkuaa47f38mFVees=,iv:s12Dt2FLx94eU3ye3wcAG8S14eDz4vzoeSyEs3MCVT4=,tag:vBq3MpeTuAIg9NUAzeLeJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
