apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../namespaces
  - ../../cert-manager/base
  - ../../cert-manager/issuers
  - ../../ingress-traefik/base
  - ../../storage/minio/base
