apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: hello-ts
  namespace: flux-system
  labels:
    platform.swhurl.com/managed: 'true'
    platform.swhurl.com/app: hello-ts
spec:
  image: ghcr.io/samclement/hello-ts
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: hello-ts-staging
  namespace: flux-system
  labels:
    platform.swhurl.com/managed: 'true'
    platform.swhurl.com/app: hello-ts
spec:
  imageRepositoryRef:
    name: hello-ts
  filterTags:
    pattern: ^(?P<run>[0-9]+)-[0-9a-f]{7,40}$
    extract: $run
  policy:
    numerical:
      order: asc
  digestReflectionPolicy: Always
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: hello-ts-staging
  namespace: flux-system
  labels:
    platform.swhurl.com/managed: 'true'
    platform.swhurl.com/app: hello-ts
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: swhurl-platform-write
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: "deploy: staging image for hello-ts\n{{ range .Changed.Changes
        }}\n- {{ .OldValue }} -> {{ .NewValue }}\n{{- end }}"
    push:
      branch: main
  update:
    path: ./apps/hello-ts/staging
    strategy: Setters
