apiVersion: v1
kind: Namespace
metadata:
  name: hello-ts-staging
  labels:
    platform.swhurl.com/managed: 'true'
    platform.swhurl.com/app: hello-ts
    platform.swhurl.com/environment: staging
    platform.swhurl.com/exposure: authenticated-web
